language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:likemartinma/devel -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev 

script:
  - qmake cuterest.pro
  - make
 
matrix:
  fast_finish: true
